version: "3"

services:
  influxdb :
    image: influxdb:latest
    container_name: dsl-influxdb
    ports:
        - "8086:8086"
    volumes:
        - ./influxdb-data:/var/lib/influxdb
  grafana :
    image: grafana/grafana:latest
    container_name: dsl-grafana
    ports:
        - "3000:3000"
    volumes:
        - ./grafana-data:/var/lib/grafana